/* files.c generated by valac 0.34.3, the Vala compiler
 * generated from files.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <stdio.h>


#define LAIR_TYPE_LAIR_FILE (lair_lair_file_get_type ())
#define LAIR_LAIR_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAIR_TYPE_LAIR_FILE, LAIRLairFile))
#define LAIR_LAIR_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAIR_TYPE_LAIR_FILE, LAIRLairFileClass))
#define LAIR_IS_LAIR_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAIR_TYPE_LAIR_FILE))
#define LAIR_IS_LAIR_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAIR_TYPE_LAIR_FILE))
#define LAIR_LAIR_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAIR_TYPE_LAIR_FILE, LAIRLairFileClass))

typedef struct _LAIRLairFile LAIRLairFile;
typedef struct _LAIRLairFileClass LAIRLairFileClass;
typedef struct _LAIRLairFilePrivate LAIRLairFilePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _LAIRLairFile {
	GObject parent_instance;
	LAIRLairFilePrivate * priv;
};

struct _LAIRLairFileClass {
	GObjectClass parent_class;
};

struct _LAIRLairFilePrivate {
	gchar* Path;
	GList* Tags;
};


static gpointer lair_lair_file_parent_class = NULL;

GType lair_lair_file_get_type (void) G_GNUC_CONST;
#define LAIR_LAIR_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LAIR_TYPE_LAIR_FILE, LAIRLairFilePrivate))
enum  {
	LAIR_LAIR_FILE_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
LAIRLairFile* lair_lair_file_new (void);
LAIRLairFile* lair_lair_file_construct (GType object_type);
LAIRLairFile* lair_lair_file_new_WithPath (const gchar* path);
LAIRLairFile* lair_lair_file_construct_WithPath (GType object_type, const gchar* path);
gchar* lair_lair_file_SetPath (LAIRLairFile* self, const gchar* path);
LAIRLairFile* lair_lair_file_new_WithPathandTags (const gchar* path, GList* tags);
LAIRLairFile* lair_lair_file_construct_WithPathandTags (GType object_type, const gchar* path, GList* tags);
GList* lair_lair_file_SetTags (LAIRLairFile* self, GList* tags);
gboolean lair_lair_file_HasTag (LAIRLairFile* self, const gchar* query);
GList* lair_lair_file_GetTags (LAIRLairFile* self);
gchar* lair_lair_file_GetPath (LAIRLairFile* self);
gboolean lair_lair_file_CheckPath (LAIRLairFile* self);
GList* lair_lair_file_LoadLineDelimitedConfig (LAIRLairFile* self);
static void lair_lair_file_finalize (GObject* obj);


static void _g_free0_ (gpointer var) {
#line 4 "/home/idk/Projects/valair/src/resmanage/files.vala"
	var = (g_free (var), NULL);
#line 73 "files.c"
}


static void _g_list_free__g_free0_ (GList* self) {
#line 4 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
#line 4 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_list_free (self);
#line 82 "files.c"
}


LAIRLairFile* lair_lair_file_construct (GType object_type) {
	LAIRLairFile * self = NULL;
#line 5 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self = (LAIRLairFile*) g_object_new (object_type, NULL);
#line 6 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_g_free0 (self->priv->Path);
#line 6 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv->Path = NULL;
#line 5 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return self;
#line 96 "files.c"
}


LAIRLairFile* lair_lair_file_new (void) {
#line 5 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return lair_lair_file_construct (LAIR_TYPE_LAIR_FILE);
#line 103 "files.c"
}


LAIRLairFile* lair_lair_file_construct_WithPath (GType object_type, const gchar* path) {
	LAIRLairFile * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 8 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 8 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self = (LAIRLairFile*) g_object_new (object_type, NULL);
#line 9 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = path;
#line 9 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp1_ = lair_lair_file_SetPath (self, _tmp0_);
#line 9 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_g_free0 (self->priv->Path);
#line 9 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv->Path = _tmp1_;
#line 8 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return self;
#line 125 "files.c"
}


LAIRLairFile* lair_lair_file_new_WithPath (const gchar* path) {
#line 8 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return lair_lair_file_construct_WithPath (LAIR_TYPE_LAIR_FILE, path);
#line 132 "files.c"
}


LAIRLairFile* lair_lair_file_construct_WithPathandTags (GType object_type, const gchar* path, GList* tags) {
	LAIRLairFile * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
#line 11 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 11 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self = (LAIRLairFile*) g_object_new (object_type, NULL);
#line 12 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = path;
#line 12 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp1_ = lair_lair_file_SetPath (self, _tmp0_);
#line 12 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_g_free0 (self->priv->Path);
#line 12 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv->Path = _tmp1_;
#line 13 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp2_ = tags;
#line 13 "/home/idk/Projects/valair/src/resmanage/files.vala"
	lair_lair_file_SetTags (self, _tmp2_);
#line 11 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return self;
#line 159 "files.c"
}


LAIRLairFile* lair_lair_file_new_WithPathandTags (const gchar* path, GList* tags) {
#line 11 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return lair_lair_file_construct_WithPathandTags (LAIR_TYPE_LAIR_FILE, path, tags);
#line 166 "files.c"
}


GList* lair_lair_file_SetTags (LAIRLairFile* self, GList* tags) {
	GList* result = NULL;
	GList* _tmp0_ = NULL;
	GList* _tmp6_ = NULL;
#line 15 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = tags;
#line 178 "files.c"
	{
		GList* tag_collection = NULL;
		GList* tag_it = NULL;
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
		tag_collection = _tmp0_;
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
		for (tag_it = tag_collection; tag_it != NULL; tag_it = tag_it->next) {
#line 186 "files.c"
			gchar* _tmp1_ = NULL;
			gchar* tag = NULL;
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp1_ = g_strdup ((const gchar*) tag_it->data);
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
			tag = _tmp1_;
#line 193 "files.c"
			{
				const gchar* _tmp2_ = NULL;
				gboolean _tmp3_ = FALSE;
#line 17 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp2_ = tag;
#line 17 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp3_ = lair_lair_file_HasTag (self, _tmp2_);
#line 17 "/home/idk/Projects/valair/src/resmanage/files.vala"
				if (_tmp3_ == FALSE) {
#line 203 "files.c"
					const gchar* _tmp4_ = NULL;
					gchar* _tmp5_ = NULL;
#line 18 "/home/idk/Projects/valair/src/resmanage/files.vala"
					_tmp4_ = tag;
#line 18 "/home/idk/Projects/valair/src/resmanage/files.vala"
					_tmp5_ = g_strdup (_tmp4_);
#line 18 "/home/idk/Projects/valair/src/resmanage/files.vala"
					self->priv->Tags = g_list_append (self->priv->Tags, _tmp5_);
#line 212 "files.c"
				}
#line 16 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_free0 (tag);
#line 216 "files.c"
			}
		}
	}
#line 21 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp6_ = self->priv->Tags;
#line 21 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = _tmp6_;
#line 21 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 226 "files.c"
}


GList* lair_lair_file_GetTags (LAIRLairFile* self) {
	GList* result = NULL;
	GList* _tmp0_ = NULL;
#line 23 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = self->priv->Tags;
#line 24 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = _tmp0_;
#line 24 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 241 "files.c"
}


gboolean lair_lair_file_HasTag (LAIRLairFile* self, const gchar* query) {
	gboolean result = FALSE;
	gboolean tmp = FALSE;
	GList* _tmp0_ = NULL;
#line 26 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 26 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (query != NULL, FALSE);
#line 27 "/home/idk/Projects/valair/src/resmanage/files.vala"
	tmp = FALSE;
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = self->priv->Tags;
#line 257 "files.c"
	{
		GList* Tag_collection = NULL;
		GList* Tag_it = NULL;
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
		Tag_collection = _tmp0_;
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
		for (Tag_it = Tag_collection; Tag_it != NULL; Tag_it = Tag_it->next) {
#line 265 "files.c"
			gchar* _tmp1_ = NULL;
			gchar* Tag = NULL;
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp1_ = g_strdup ((const gchar*) Tag_it->data);
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
			Tag = _tmp1_;
#line 272 "files.c"
			{
				const gchar* _tmp2_ = NULL;
				const gchar* _tmp3_ = NULL;
#line 29 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp2_ = query;
#line 29 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp3_ = Tag;
#line 29 "/home/idk/Projects/valair/src/resmanage/files.vala"
				if (g_strcmp0 (_tmp2_, _tmp3_) == 0) {
#line 30 "/home/idk/Projects/valair/src/resmanage/files.vala"
					tmp = TRUE;
#line 31 "/home/idk/Projects/valair/src/resmanage/files.vala"
					_g_free0 (Tag);
#line 31 "/home/idk/Projects/valair/src/resmanage/files.vala"
					break;
#line 288 "files.c"
				}
#line 28 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_free0 (Tag);
#line 292 "files.c"
			}
		}
	}
#line 34 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = tmp;
#line 34 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 300 "files.c"
}


gchar* lair_lair_file_GetPath (LAIRLairFile* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 36 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = self->priv->Path;
#line 37 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 37 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = _tmp1_;
#line 37 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 318 "files.c"
}


gchar* lair_lair_file_SetPath (LAIRLairFile* self, const gchar* path) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 39 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 39 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (path != NULL, NULL);
#line 40 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = path;
#line 40 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp1_ = g_file_test (_tmp0_, G_FILE_TEST_EXISTS);
#line 40 "/home/idk/Projects/valair/src/resmanage/files.vala"
	if (_tmp1_) {
#line 338 "files.c"
		const gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
#line 41 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp2_ = path;
#line 41 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp3_ = g_strdup (_tmp2_);
#line 41 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_free0 (self->priv->Path);
#line 41 "/home/idk/Projects/valair/src/resmanage/files.vala"
		self->priv->Path = _tmp3_;
#line 349 "files.c"
	} else {
#line 43 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_free0 (self->priv->Path);
#line 43 "/home/idk/Projects/valair/src/resmanage/files.vala"
		self->priv->Path = NULL;
#line 355 "files.c"
	}
#line 45 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp4_ = path;
#line 45 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 45 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = _tmp5_;
#line 45 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 365 "files.c"
}


gboolean lair_lair_file_CheckPath (LAIRLairFile* self) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
#line 47 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 48 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = self->priv->Path;
#line 48 "/home/idk/Projects/valair/src/resmanage/files.vala"
	if (_tmp0_ != NULL) {
#line 49 "/home/idk/Projects/valair/src/resmanage/files.vala"
		result = TRUE;
#line 49 "/home/idk/Projects/valair/src/resmanage/files.vala"
		return result;
#line 382 "files.c"
	} else {
#line 51 "/home/idk/Projects/valair/src/resmanage/files.vala"
		result = FALSE;
#line 51 "/home/idk/Projects/valair/src/resmanage/files.vala"
		return result;
#line 388 "files.c"
	}
}


GList* lair_lair_file_LoadLineDelimitedConfig (LAIRLairFile* self) {
	GList* result = NULL;
	GList* tmp = NULL;
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GError * _inner_error_ = NULL;
#line 54 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 55 "/home/idk/Projects/valair/src/resmanage/files.vala"
	tmp = NULL;
#line 56 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp0_ = self->priv->Path;
#line 56 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp1_ = g_file_new_for_path (_tmp0_);
#line 56 "/home/idk/Projects/valair/src/resmanage/files.vala"
	file = _tmp1_;
#line 57 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp2_ = file;
#line 57 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
#line 57 "/home/idk/Projects/valair/src/resmanage/files.vala"
	if (!_tmp3_) {
#line 418 "files.c"
		FILE* _tmp4_ = NULL;
		GFile* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp4_ = stderr;
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp5_ = file;
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp6_ = g_file_get_path (_tmp5_);
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp7_ = _tmp6_;
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		fprintf (_tmp4_, "File '%s' doesn't exist.\n", _tmp7_);
#line 58 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_free0 (_tmp7_);
#line 435 "files.c"
	}
	{
		GFileInputStream* _tmp8_ = NULL;
		GFile* _tmp9_ = NULL;
		GFileInputStream* _tmp10_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp11_ = NULL;
		gchar* line = NULL;
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp9_ = file;
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp10_ = g_file_read (_tmp9_, NULL, &_inner_error_);
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp8_ = _tmp10_;
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 452 "files.c"
			goto __catch0_g_error;
		}
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp11_ = g_data_input_stream_new ((GInputStream*) _tmp8_);
#line 63 "/home/idk/Projects/valair/src/resmanage/files.vala"
		dis = _tmp11_;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
		while (TRUE) {
#line 461 "files.c"
			gchar* _tmp12_ = NULL;
			GDataInputStream* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			gboolean _tmp18_ = FALSE;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp13_ = dis;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp14_ = g_data_input_stream_read_line (_tmp13_, NULL, NULL, &_inner_error_);
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp12_ = _tmp14_;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_free0 (line);
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_object_unref0 (dis);
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_object_unref0 (_tmp8_);
#line 483 "files.c"
				goto __catch0_g_error;
			}
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp15_ = _tmp12_;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp12_ = NULL;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_g_free0 (line);
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			line = _tmp15_;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp16_ = line;
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			if (!(_tmp16_ != NULL)) {
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_g_free0 (_tmp12_);
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
				break;
#line 502 "files.c"
			}
#line 67 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp17_ = line;
#line 67 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_tmp18_ = g_file_test (_tmp17_, G_FILE_TEST_EXISTS);
#line 67 "/home/idk/Projects/valair/src/resmanage/files.vala"
			if (_tmp18_) {
#line 510 "files.c"
				const gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
#line 68 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp19_ = line;
#line 68 "/home/idk/Projects/valair/src/resmanage/files.vala"
				_tmp20_ = g_strdup (_tmp19_);
#line 68 "/home/idk/Projects/valair/src/resmanage/files.vala"
				tmp = g_list_append (tmp, _tmp20_);
#line 519 "files.c"
			}
#line 66 "/home/idk/Projects/valair/src/resmanage/files.vala"
			_g_free0 (_tmp12_);
#line 523 "files.c"
		}
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_free0 (line);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_object_unref0 (dis);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_object_unref0 (_tmp8_);
#line 531 "files.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp21_ = NULL;
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		e = _inner_error_;
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_inner_error_ = NULL;
#line 72 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_tmp21_ = e->message;
#line 72 "/home/idk/Projects/valair/src/resmanage/files.vala"
		g_error ("files.vala:72: %s", _tmp21_);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_error_free0 (e);
#line 548 "files.c"
	}
	__finally0:
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		_g_object_unref0 (file);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		__g_list_free__g_free0_0 (tmp);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		g_clear_error (&_inner_error_);
#line 60 "/home/idk/Projects/valair/src/resmanage/files.vala"
		return NULL;
#line 563 "files.c"
	}
#line 74 "/home/idk/Projects/valair/src/resmanage/files.vala"
	result = tmp;
#line 74 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_g_object_unref0 (file);
#line 74 "/home/idk/Projects/valair/src/resmanage/files.vala"
	return result;
#line 571 "files.c"
}


static void lair_lair_file_class_init (LAIRLairFileClass * klass) {
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	lair_lair_file_parent_class = g_type_class_peek_parent (klass);
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	g_type_class_add_private (klass, sizeof (LAIRLairFilePrivate));
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	G_OBJECT_CLASS (klass)->finalize = lair_lair_file_finalize;
#line 582 "files.c"
}


static void lair_lair_file_instance_init (LAIRLairFile * self) {
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv = LAIR_LAIR_FILE_GET_PRIVATE (self);
#line 3 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv->Path = NULL;
#line 4 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self->priv->Tags = NULL;
#line 593 "files.c"
}


static void lair_lair_file_finalize (GObject* obj) {
	LAIRLairFile * self;
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LAIR_TYPE_LAIR_FILE, LAIRLairFile);
#line 3 "/home/idk/Projects/valair/src/resmanage/files.vala"
	_g_free0 (self->priv->Path);
#line 4 "/home/idk/Projects/valair/src/resmanage/files.vala"
	__g_list_free__g_free0_0 (self->priv->Tags);
#line 2 "/home/idk/Projects/valair/src/resmanage/files.vala"
	G_OBJECT_CLASS (lair_lair_file_parent_class)->finalize (obj);
#line 607 "files.c"
}


GType lair_lair_file_get_type (void) {
	static volatile gsize lair_lair_file_type_id__volatile = 0;
	if (g_once_init_enter (&lair_lair_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LAIRLairFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lair_lair_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LAIRLairFile), 0, (GInstanceInitFunc) lair_lair_file_instance_init, NULL };
		GType lair_lair_file_type_id;
		lair_lair_file_type_id = g_type_register_static (G_TYPE_OBJECT, "LAIRLairFile", &g_define_type_info, 0);
		g_once_init_leave (&lair_lair_file_type_id__volatile, lair_lair_file_type_id);
	}
	return lair_lair_file_type_id__volatile;
}



