/* images.c generated by valac 0.34.3, the Vala compiler
 * generated from images.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_surface.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_image.h>


#define LAIR_TYPE_LAIR_FILE (lair_lair_file_get_type ())
#define LAIR_LAIR_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAIR_TYPE_LAIR_FILE, LAIRLairFile))
#define LAIR_LAIR_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAIR_TYPE_LAIR_FILE, LAIRLairFileClass))
#define LAIR_IS_LAIR_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAIR_TYPE_LAIR_FILE))
#define LAIR_IS_LAIR_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAIR_TYPE_LAIR_FILE))
#define LAIR_LAIR_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAIR_TYPE_LAIR_FILE, LAIRLairFileClass))

typedef struct _LAIRLairFile LAIRLairFile;
typedef struct _LAIRLairFileClass LAIRLairFileClass;
typedef struct _LAIRLairFilePrivate LAIRLairFilePrivate;

#define LAIR_TYPE_IMAGE (lair_image_get_type ())
#define LAIR_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAIR_TYPE_IMAGE, LAIRImage))
#define LAIR_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAIR_TYPE_IMAGE, LAIRImageClass))
#define LAIR_IS_IMAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAIR_TYPE_IMAGE))
#define LAIR_IS_IMAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAIR_TYPE_IMAGE))
#define LAIR_IMAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAIR_TYPE_IMAGE, LAIRImageClass))

typedef struct _LAIRImage LAIRImage;
typedef struct _LAIRImageClass LAIRImageClass;
typedef struct _LAIRImagePrivate LAIRImagePrivate;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _LAIRLairFile {
	GObject parent_instance;
	LAIRLairFilePrivate * priv;
};

struct _LAIRLairFileClass {
	GObjectClass parent_class;
};

struct _LAIRImage {
	LAIRLairFile parent_instance;
	LAIRImagePrivate * priv;
};

struct _LAIRImageClass {
	LAIRLairFileClass parent_class;
};

struct _LAIRImagePrivate {
	SDL_Surface* surface;
};


static gpointer lair_image_parent_class = NULL;

GType lair_lair_file_get_type (void) G_GNUC_CONST;
GType lair_image_get_type (void) G_GNUC_CONST;
#define LAIR_IMAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LAIR_TYPE_IMAGE, LAIRImagePrivate))
enum  {
	LAIR_IMAGE_DUMMY_PROPERTY
};
LAIRImage* lair_image_new (const gchar* Path);
LAIRImage* lair_image_construct (GType object_type, const gchar* Path);
LAIRLairFile* lair_lair_file_new_WithPath (const gchar* path);
LAIRLairFile* lair_lair_file_construct_WithPath (GType object_type, const gchar* path);
gboolean lair_image_ImageLoad (LAIRImage* self, const gchar* Path);
gchar* lair_lair_file_SetPath (LAIRLairFile* self, const gchar* path);
gboolean lair_lair_file_CheckPath (LAIRLairFile* self);
gchar* lair_lair_file_GetPath (LAIRLairFile* self);
gboolean lair_image_CheckImage (LAIRImage* self);
SDL_Surface* lair_image_GetImage (LAIRImage* self);
static void lair_image_finalize (GObject* obj);


LAIRImage* lair_image_construct (GType object_type, const gchar* Path) {
	LAIRImage * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 8 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_return_val_if_fail (Path != NULL, NULL);
#line 9 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp0_ = Path;
#line 9 "/home/idk/Projects/valair/src/resmanage/images.vala"
	self = (LAIRImage*) lair_lair_file_construct_WithPath (object_type, _tmp0_);
#line 10 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp1_ = Path;
#line 10 "/home/idk/Projects/valair/src/resmanage/images.vala"
	lair_image_ImageLoad (self, _tmp1_);
#line 8 "/home/idk/Projects/valair/src/resmanage/images.vala"
	return self;
#line 98 "images.c"
}


LAIRImage* lair_image_new (const gchar* Path) {
#line 8 "/home/idk/Projects/valair/src/resmanage/images.vala"
	return lair_image_construct (LAIR_TYPE_IMAGE, Path);
#line 105 "images.c"
}


gboolean lair_image_ImageLoad (LAIRImage* self, const gchar* Path) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gboolean tmp = FALSE;
	gboolean _tmp3_ = FALSE;
#line 12 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 12 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_return_val_if_fail (Path != NULL, FALSE);
#line 13 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp0_ = Path;
#line 13 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp1_ = lair_lair_file_SetPath ((LAIRLairFile*) self, _tmp0_);
#line 13 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp2_ = _tmp1_;
#line 13 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_g_free0 (_tmp2_);
#line 14 "/home/idk/Projects/valair/src/resmanage/images.vala"
	tmp = FALSE;
#line 15 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp3_ = lair_lair_file_CheckPath ((LAIRLairFile*) self);
#line 15 "/home/idk/Projects/valair/src/resmanage/images.vala"
	if (_tmp3_) {
#line 134 "images.c"
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		SDL_Surface* _tmp6_ = NULL;
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		_tmp4_ = lair_lair_file_GetPath ((LAIRLairFile*) self);
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		_tmp5_ = _tmp4_;
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		_tmp6_ = IMG_Load (_tmp5_);
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		_SDL_FreeSurface0 (self->priv->surface);
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		self->priv->surface = _tmp6_;
#line 16 "/home/idk/Projects/valair/src/resmanage/images.vala"
		_g_free0 (_tmp5_);
#line 17 "/home/idk/Projects/valair/src/resmanage/images.vala"
		tmp = TRUE;
#line 152 "images.c"
	}
#line 19 "/home/idk/Projects/valair/src/resmanage/images.vala"
	result = tmp;
#line 19 "/home/idk/Projects/valair/src/resmanage/images.vala"
	return result;
#line 158 "images.c"
}


gboolean lair_image_CheckImage (LAIRImage* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
#line 21 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 22 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp0_ = lair_lair_file_CheckPath ((LAIRLairFile*) self);
#line 22 "/home/idk/Projects/valair/src/resmanage/images.vala"
	if (_tmp0_) {
#line 23 "/home/idk/Projects/valair/src/resmanage/images.vala"
		result = TRUE;
#line 23 "/home/idk/Projects/valair/src/resmanage/images.vala"
		return result;
#line 175 "images.c"
	} else {
#line 25 "/home/idk/Projects/valair/src/resmanage/images.vala"
		result = FALSE;
#line 25 "/home/idk/Projects/valair/src/resmanage/images.vala"
		return result;
#line 181 "images.c"
	}
}


static gpointer _SDL_Surface_up0 (gpointer self) {
#line 29 "/home/idk/Projects/valair/src/resmanage/images.vala"
	return self ? SDL_Surface_up (self) : NULL;
#line 189 "images.c"
}


SDL_Surface* lair_image_GetImage (LAIRImage* self) {
	SDL_Surface* result = NULL;
	SDL_Surface* _tmp0_ = NULL;
	SDL_Surface* _tmp1_ = NULL;
#line 28 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 29 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp0_ = self->priv->surface;
#line 29 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_tmp1_ = _SDL_Surface_up0 (_tmp0_);
#line 29 "/home/idk/Projects/valair/src/resmanage/images.vala"
	result = _tmp1_;
#line 29 "/home/idk/Projects/valair/src/resmanage/images.vala"
	return result;
#line 207 "images.c"
}


static void lair_image_class_init (LAIRImageClass * klass) {
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	lair_image_parent_class = g_type_class_peek_parent (klass);
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	g_type_class_add_private (klass, sizeof (LAIRImagePrivate));
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	G_OBJECT_CLASS (klass)->finalize = lair_image_finalize;
#line 218 "images.c"
}


static void lair_image_instance_init (LAIRImage * self) {
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	self->priv = LAIR_IMAGE_GET_PRIVATE (self);
#line 225 "images.c"
}


static void lair_image_finalize (GObject* obj) {
	LAIRImage * self;
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LAIR_TYPE_IMAGE, LAIRImage);
#line 7 "/home/idk/Projects/valair/src/resmanage/images.vala"
	_SDL_FreeSurface0 (self->priv->surface);
#line 6 "/home/idk/Projects/valair/src/resmanage/images.vala"
	G_OBJECT_CLASS (lair_image_parent_class)->finalize (obj);
#line 237 "images.c"
}


GType lair_image_get_type (void) {
	static volatile gsize lair_image_type_id__volatile = 0;
	if (g_once_init_enter (&lair_image_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LAIRImageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lair_image_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LAIRImage), 0, (GInstanceInitFunc) lair_image_instance_init, NULL };
		GType lair_image_type_id;
		lair_image_type_id = g_type_register_static (LAIR_TYPE_LAIR_FILE, "LAIRImage", &g_define_type_info, 0);
		g_once_init_leave (&lair_image_type_id__volatile, lair_image_type_id);
	}
	return lair_image_type_id__volatile;
}



