/* main.c generated by valac 0.34.3, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_timer.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_ttf.h>
#include <gobject/gvaluecollector.h>


#define LAIR_TYPE_LAIR (lair_lair_get_type ())
#define LAIR_LAIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAIR_TYPE_LAIR, LAIRLair))
#define LAIR_LAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAIR_TYPE_LAIR, LAIRLairClass))
#define LAIR_IS_LAIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAIR_TYPE_LAIR))
#define LAIR_IS_LAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAIR_TYPE_LAIR))
#define LAIR_LAIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAIR_TYPE_LAIR, LAIRLairClass))

typedef struct _LAIRLair LAIRLair;
typedef struct _LAIRLairClass LAIRLairClass;
typedef struct _LAIRLairPrivate LAIRLairPrivate;

#define LAIR_TYPE_FILE_DB (lair_file_db_get_type ())
#define LAIR_FILE_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LAIR_TYPE_FILE_DB, LAIRFileDB))
#define LAIR_FILE_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LAIR_TYPE_FILE_DB, LAIRFileDBClass))
#define LAIR_IS_FILE_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LAIR_TYPE_FILE_DB))
#define LAIR_IS_FILE_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LAIR_TYPE_FILE_DB))
#define LAIR_FILE_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LAIR_TYPE_FILE_DB, LAIRFileDBClass))

typedef struct _LAIRFileDB LAIRFileDB;
typedef struct _LAIRFileDBClass LAIRFileDBClass;
#define _lair_file_db_unref0(var) ((var == NULL) ? NULL : (var = (lair_file_db_unref (var), NULL)))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))
#define _SDL_DestroyRenderer0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyRenderer (var), NULL)))
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _lair_lair_unref0(var) ((var == NULL) ? NULL : (var = (lair_lair_unref (var), NULL)))
typedef struct _LAIRParamSpecLair LAIRParamSpecLair;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _LAIRLair {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LAIRLairPrivate * priv;
};

struct _LAIRLairClass {
	GTypeClass parent_class;
	void (*finalize) (LAIRLair *self);
};

struct _LAIRLairPrivate {
	LAIRFileDB* Resources;
	SDL_Window* window;
	SDL_Renderer* window_renderer;
	SDL_Surface* surface;
	SDL_Surface* LairSurface;
};

struct _LAIRParamSpecLair {
	GParamSpec parent_instance;
};


static gpointer lair_lair_parent_class = NULL;

gpointer lair_lair_ref (gpointer instance);
void lair_lair_unref (gpointer instance);
GParamSpec* lair_param_spec_lair (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void lair_value_set_lair (GValue* value, gpointer v_object);
void lair_value_take_lair (GValue* value, gpointer v_object);
gpointer lair_value_get_lair (const GValue* value);
GType lair_lair_get_type (void) G_GNUC_CONST;
gpointer lair_file_db_ref (gpointer instance);
void lair_file_db_unref (gpointer instance);
GParamSpec* lair_param_spec_file_db (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void lair_value_set_file_db (GValue* value, gpointer v_object);
void lair_value_take_file_db (GValue* value, gpointer v_object);
gpointer lair_value_get_file_db (const GValue* value);
GType lair_file_db_get_type (void) G_GNUC_CONST;
#define LAIR_LAIR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LAIR_TYPE_LAIR, LAIRLairPrivate))
enum  {
	LAIR_LAIR_DUMMY_PROPERTY
};
LAIRFileDB* lair_file_db_new (const gchar* imgList, const gchar* sndList, const gchar* ttfList);
LAIRFileDB* lair_file_db_construct (GType object_type, const gchar* imgList, const gchar* sndList, const gchar* ttfList);
void lair_lair_run (LAIRLair* self);
void lair_lair_load_media (LAIRLair* self);
gboolean lair_file_db_LoadFiles (LAIRFileDB* self);
void lair_lair_init (LAIRLair* self);
void lair_lair_main (void);
LAIRLair* lair_lair_new (void);
LAIRLair* lair_lair_construct (GType object_type);
static void lair_lair_finalize (LAIRLair* obj);


void lair_lair_run (LAIRLair* self) {
	SDL_Surface* _tmp0_ = NULL;
	SDL_Surface* _tmp1_ = NULL;
	SDL_Window* _tmp2_ = NULL;
#line 17 "/home/idk/Projects/valair/src/main.vala"
	g_return_if_fail (self != NULL);
#line 18 "/home/idk/Projects/valair/src/main.vala"
	_tmp0_ = self->priv->LairSurface;
#line 18 "/home/idk/Projects/valair/src/main.vala"
	_tmp1_ = self->priv->surface;
#line 18 "/home/idk/Projects/valair/src/main.vala"
	SDL_BlitSurface (_tmp0_, NULL, _tmp1_, NULL);
#line 19 "/home/idk/Projects/valair/src/main.vala"
	_tmp2_ = self->priv->window;
#line 19 "/home/idk/Projects/valair/src/main.vala"
	SDL_UpdateWindowSurface (_tmp2_);
#line 20 "/home/idk/Projects/valair/src/main.vala"
	SDL_Delay ((guint32) 2000);
#line 125 "main.c"
}


void lair_lair_load_media (LAIRLair* self) {
	SDL_Surface* _tmp0_ = NULL;
	LAIRFileDB* _tmp1_ = NULL;
#line 22 "/home/idk/Projects/valair/src/main.vala"
	g_return_if_fail (self != NULL);
#line 23 "/home/idk/Projects/valair/src/main.vala"
	_tmp0_ = IMG_Load ("resources/hello_world.bmp");
#line 23 "/home/idk/Projects/valair/src/main.vala"
	_SDL_FreeSurface0 (self->priv->LairSurface);
#line 23 "/home/idk/Projects/valair/src/main.vala"
	self->priv->LairSurface = _tmp0_;
#line 24 "/home/idk/Projects/valair/src/main.vala"
	_tmp1_ = self->priv->Resources;
#line 24 "/home/idk/Projects/valair/src/main.vala"
	lair_file_db_LoadFiles (_tmp1_);
#line 144 "main.c"
}


void lair_lair_init (LAIRLair* self) {
	SDL_Window* _tmp0_ = NULL;
	SDL_Window* _tmp1_ = NULL;
	SDL_Renderer* _tmp2_ = NULL;
	SDL_Window* _tmp3_ = NULL;
	SDL_Surface* _tmp4_ = NULL;
	SDL_Window* _tmp5_ = NULL;
	SDL_Renderer* _tmp6_ = NULL;
#line 26 "/home/idk/Projects/valair/src/main.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/idk/Projects/valair/src/main.vala"
	SDL_Init ((guint32) (SDL_INIT_EVERYTHING | IMG_INIT_JPG|IMG_INIT_PNG|IMG_INIT_TIF|IMG_INIT_WEBP));
#line 28 "/home/idk/Projects/valair/src/main.vala"
	TTF_Init ();
#line 30 "/home/idk/Projects/valair/src/main.vala"
	_tmp0_ = SDL_CreateWindow ("LAIR!", (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, 640, 480, (guint32) SDL_WINDOW_SHOWN);
#line 30 "/home/idk/Projects/valair/src/main.vala"
	_SDL_DestroyWindow0 (self->priv->window);
#line 30 "/home/idk/Projects/valair/src/main.vala"
	self->priv->window = _tmp0_;
#line 31 "/home/idk/Projects/valair/src/main.vala"
	_tmp1_ = self->priv->window;
#line 31 "/home/idk/Projects/valair/src/main.vala"
	_tmp2_ = SDL_CreateRenderer (_tmp1_, -1, (guint32) (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC));
#line 31 "/home/idk/Projects/valair/src/main.vala"
	_SDL_DestroyRenderer0 (self->priv->window_renderer);
#line 31 "/home/idk/Projects/valair/src/main.vala"
	self->priv->window_renderer = _tmp2_;
#line 33 "/home/idk/Projects/valair/src/main.vala"
	_tmp3_ = self->priv->window;
#line 33 "/home/idk/Projects/valair/src/main.vala"
	_tmp4_ = SDL_GetWindowSurface (_tmp3_);
#line 33 "/home/idk/Projects/valair/src/main.vala"
	_SDL_FreeSurface0 (self->priv->surface);
#line 33 "/home/idk/Projects/valair/src/main.vala"
	self->priv->surface = _tmp4_;
#line 34 "/home/idk/Projects/valair/src/main.vala"
	lair_lair_load_media (self);
#line 36 "/home/idk/Projects/valair/src/main.vala"
	_tmp5_ = self->priv->window;
#line 36 "/home/idk/Projects/valair/src/main.vala"
	SDL_ShowWindow (_tmp5_);
#line 37 "/home/idk/Projects/valair/src/main.vala"
	_tmp6_ = self->priv->window_renderer;
#line 37 "/home/idk/Projects/valair/src/main.vala"
	_vala_assert (_tmp6_ == NULL, "window_renderer == null");
#line 194 "main.c"
}


void lair_lair_main (void) {
	LAIRLair* app = NULL;
	LAIRLair* _tmp0_ = NULL;
#line 40 "/home/idk/Projects/valair/src/main.vala"
	_tmp0_ = lair_lair_new ();
#line 40 "/home/idk/Projects/valair/src/main.vala"
	app = _tmp0_;
#line 41 "/home/idk/Projects/valair/src/main.vala"
	lair_lair_init (app);
#line 42 "/home/idk/Projects/valair/src/main.vala"
	lair_lair_run (app);
#line 39 "/home/idk/Projects/valair/src/main.vala"
	_lair_lair_unref0 (app);
#line 211 "main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 39 "/home/idk/Projects/valair/src/main.vala"
	lair_lair_main ();
#line 39 "/home/idk/Projects/valair/src/main.vala"
	return 0;
#line 223 "main.c"
}


LAIRLair* lair_lair_construct (GType object_type) {
	LAIRLair* self = NULL;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	self = (LAIRLair*) g_type_create_instance (object_type);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return self;
#line 233 "main.c"
}


LAIRLair* lair_lair_new (void) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return lair_lair_construct (LAIR_TYPE_LAIR);
#line 240 "main.c"
}


static void lair_value_lair_init (GValue* value) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	value->data[0].v_pointer = NULL;
#line 247 "main.c"
}


static void lair_value_lair_free_value (GValue* value) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (value->data[0].v_pointer) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		lair_lair_unref (value->data[0].v_pointer);
#line 256 "main.c"
	}
}


static void lair_value_lair_copy_value (const GValue* src_value, GValue* dest_value) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (src_value->data[0].v_pointer) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		dest_value->data[0].v_pointer = lair_lair_ref (src_value->data[0].v_pointer);
#line 266 "main.c"
	} else {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		dest_value->data[0].v_pointer = NULL;
#line 270 "main.c"
	}
}


static gpointer lair_value_lair_peek_pointer (const GValue* value) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return value->data[0].v_pointer;
#line 278 "main.c"
}


static gchar* lair_value_lair_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (collect_values[0].v_pointer) {
#line 285 "main.c"
		LAIRLair* object;
		object = collect_values[0].v_pointer;
#line 8 "/home/idk/Projects/valair/src/main.vala"
		if (object->parent_instance.g_class == NULL) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 292 "main.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 296 "main.c"
		}
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = lair_lair_ref (object);
#line 300 "main.c"
	} else {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = NULL;
#line 304 "main.c"
	}
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return NULL;
#line 308 "main.c"
}


static gchar* lair_value_lair_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	LAIRLair** object_p;
	object_p = collect_values[0].v_pointer;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (!object_p) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 319 "main.c"
	}
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (!value->data[0].v_pointer) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		*object_p = NULL;
#line 325 "main.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		*object_p = value->data[0].v_pointer;
#line 329 "main.c"
	} else {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		*object_p = lair_lair_ref (value->data[0].v_pointer);
#line 333 "main.c"
	}
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return NULL;
#line 337 "main.c"
}


GParamSpec* lair_param_spec_lair (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	LAIRParamSpecLair* spec;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_return_val_if_fail (g_type_is_a (object_type, LAIR_TYPE_LAIR), NULL);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return G_PARAM_SPEC (spec);
#line 351 "main.c"
}


gpointer lair_value_get_lair (const GValue* value) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LAIR_TYPE_LAIR), NULL);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return value->data[0].v_pointer;
#line 360 "main.c"
}


void lair_value_set_lair (GValue* value, gpointer v_object) {
	LAIRLair* old;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LAIR_TYPE_LAIR));
#line 8 "/home/idk/Projects/valair/src/main.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (v_object) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, LAIR_TYPE_LAIR));
#line 8 "/home/idk/Projects/valair/src/main.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = v_object;
#line 8 "/home/idk/Projects/valair/src/main.vala"
		lair_lair_ref (value->data[0].v_pointer);
#line 380 "main.c"
	} else {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = NULL;
#line 384 "main.c"
	}
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (old) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		lair_lair_unref (old);
#line 390 "main.c"
	}
}


void lair_value_take_lair (GValue* value, gpointer v_object) {
	LAIRLair* old;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, LAIR_TYPE_LAIR));
#line 8 "/home/idk/Projects/valair/src/main.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (v_object) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, LAIR_TYPE_LAIR));
#line 8 "/home/idk/Projects/valair/src/main.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = v_object;
#line 409 "main.c"
	} else {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		value->data[0].v_pointer = NULL;
#line 413 "main.c"
	}
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (old) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		lair_lair_unref (old);
#line 419 "main.c"
	}
}


static void lair_lair_class_init (LAIRLairClass * klass) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
	lair_lair_parent_class = g_type_class_peek_parent (klass);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	((LAIRLairClass *) klass)->finalize = lair_lair_finalize;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_type_class_add_private (klass, sizeof (LAIRLairPrivate));
#line 431 "main.c"
}


static void lair_lair_instance_init (LAIRLair * self) {
	LAIRFileDB* _tmp0_ = NULL;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	self->priv = LAIR_LAIR_GET_PRIVATE (self);
#line 9 "/home/idk/Projects/valair/src/main.vala"
	_tmp0_ = lair_file_db_new ("/etc/lair/images.list", "/etc/lair/sounds.list", "/etc/lair/fonts.list");
#line 9 "/home/idk/Projects/valair/src/main.vala"
	self->priv->Resources = _tmp0_;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	self->ref_count = 1;
#line 445 "main.c"
}


static void lair_lair_finalize (LAIRLair* obj) {
	LAIRLair * self;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, LAIR_TYPE_LAIR, LAIRLair);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_signal_handlers_destroy (self);
#line 15 "/home/idk/Projects/valair/src/main.vala"
	SDL_Quit ();
#line 9 "/home/idk/Projects/valair/src/main.vala"
	_lair_file_db_unref0 (self->priv->Resources);
#line 10 "/home/idk/Projects/valair/src/main.vala"
	_SDL_DestroyWindow0 (self->priv->window);
#line 11 "/home/idk/Projects/valair/src/main.vala"
	_SDL_DestroyRenderer0 (self->priv->window_renderer);
#line 12 "/home/idk/Projects/valair/src/main.vala"
	_SDL_FreeSurface0 (self->priv->surface);
#line 13 "/home/idk/Projects/valair/src/main.vala"
	_SDL_FreeSurface0 (self->priv->LairSurface);
#line 467 "main.c"
}


GType lair_lair_get_type (void) {
	static volatile gsize lair_lair_type_id__volatile = 0;
	if (g_once_init_enter (&lair_lair_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { lair_value_lair_init, lair_value_lair_free_value, lair_value_lair_copy_value, lair_value_lair_peek_pointer, "p", lair_value_lair_collect_value, "p", lair_value_lair_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (LAIRLairClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) lair_lair_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LAIRLair), 0, (GInstanceInitFunc) lair_lair_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType lair_lair_type_id;
		lair_lair_type_id = g_type_register_fundamental (g_type_fundamental_next (), "LAIRLair", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&lair_lair_type_id__volatile, lair_lair_type_id);
	}
	return lair_lair_type_id__volatile;
}


gpointer lair_lair_ref (gpointer instance) {
	LAIRLair* self;
	self = instance;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	g_atomic_int_inc (&self->ref_count);
#line 8 "/home/idk/Projects/valair/src/main.vala"
	return instance;
#line 492 "main.c"
}


void lair_lair_unref (gpointer instance) {
	LAIRLair* self;
	self = instance;
#line 8 "/home/idk/Projects/valair/src/main.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 8 "/home/idk/Projects/valair/src/main.vala"
		LAIR_LAIR_GET_CLASS (self)->finalize (self);
#line 8 "/home/idk/Projects/valair/src/main.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 505 "main.c"
	}
}



